### ISSUE TITLE
[Bug] main CI red after the 2026-08-15 merge wave: docs smoke-spec TS18048 + inventory-service gofmt

### ISSUE THREAD

**Issue by xdfkenny** [xdfkenny/Astra-System#492]
## Summary

Found while syncing after the merge wave (local main pulled to fac418f). The last three main CI runs concluded **failure**:

- \`ts-checks / lint-ts\` (also failing test-unit-ts / build-ts via the same gate): \`astra-service/apps/docs/src/smoke/build.spec.ts(29,14)\` and \`(30,67)\` — \`error TS18048: 'link' is possibly 'undefined'\` (docs smoke spec typecheck; arrived with the docs-app batch #472/#474/#482 era).
- \`go-checks / lint-go (astra-service/services/inventory-service)\`: the \`gofmt -l .\` guard step fails — a file merged by #458 (infinite-stock) isn't gofmt-clean.

Both are one-line-class fixes; the red gate hides real signal for every open PR (incl. #491).

## Acceptance criteria

- [ ] build.spec.ts TS18048 fixed (guard the possibly-undefined \`link\`)
- [ ] \`gofmt -l astra-service/services/inventory-service\` clean
- [ ] A main run concludes success (allowing the documented linux/arm64 syncd runtime cost)

## Priority rationale

prio:high — red main degrades the merge gate for every PR and violates the board's own green-main convention.

**Comment by xdfkenny** [comment]
🙋 Claimed by astra-agent — owner-directed session ("start fixing CI/CD"). Premise verified against live runs: 6/6 last main runs red. Run 31865156016 shows the two classes in the issue body (docs smoke-spec TS18048 gating lint-ts/build-ts/test-unit-ts; inventory-service gofmt). Latest run 31923079702 additionally shows kiosk/kiosk-unified docker builds failing on @astra/design-system BottomSheet.tsx TS2307 (Cannot find module '../i18n') — required for acceptance criterion 3 (green main run). Plan: worktree off origin/main → fix all three → scoped commit → PR through pipeline. Local parity: pnpm typecheck (docs), gofmt -l (inventory-service), design-system tsc build.

**Comment by xdfkenny** [comment]
Pushed astra-agent/issue-492 (#492) — PR #494 open, in pipeline (pipeline:scanning). Scope grew to 4 latent breaks found behind the red gate: (1) docs smoke-spec TS18048, (2) inventory-service gofmt, (3) design-system BottomSheet imported kiosk-only '../i18n' → TS2307 in every kiosk docker build (fixed via closeLabel prop; kiosk callers pass t("common.close")), (4) orphaned kiosk BottomSheet.spec.tsx (imported a moved-away file) + stale #429-era StatusBar spec (pre-#448 semantics). Local parity all green — evidence table in the PR body.

**Comment by xdfkenny** [comment]
Scope update: the red lint gates were transitively skipping test-unit-go + test-e2e (needs + !failure()), so four more latent breaks surfaced once the PR turned the lint gates green: order-service fixtures missing Finalized:true (#393 guard), admin-graphql testutil's stale migration subset (missing 0006 sync_heartbeats) + KPI test's shared-cart seeding vs 0010's unique index, and the purchase-flow e2e's stale 'Biometric' dialog name (renamed intentionally in #405). All fixed and amended into the same scoped commit (7115309) on PR #494. Local parity green across Go (3 modules), workspace typecheck/build, kiosk+design-system+docs tests; kiosk e2e local run blocked by the owner's docker stack holding :5180 — CI is the authority for that gate.

**Comment by xdfkenny** [comment]
Resuelto en b5a63e50 — merged via PR #494 (owner, 2026-08-16). Labels cleaned post-merge.
